languages:
  Ruby: true
  JavaScript: false
  PHP: false
  Python: false
exclude_paths:
- "doc"
- "mrblib"
- "tests"
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25
