engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25
exclude_paths:
- doc/**
- mrblib/**
- tests/**
- certs/**
- .git/**
